// Regenerates ui/app/version.ts from app.config.json (app.version) plus git
// build metadata (short commit hash + commit date). Wired into the `build` and
// `deploy` npm scripts so the in-app version footer and About page always match
// the deployed app version — no manual edits needed.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8"));
const version = cfg?.app?.version;

if (!version) {
  console.error("[sync-version] could not read app.version from app.config.json");
  process.exit(1);
}

function git(command, fallback) {
  try {
    return execSync(command, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const commitHash = git("git rev-parse --short HEAD", "unknown");
const commitDate = git("git log -1 --format=%cI", "");

const out =
  `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n` +
  `// Sourced from app.config.json (app.version) + git; regenerated on build/deploy.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n` +
  `export const COMMIT_HASH = ${JSON.stringify(commitHash)};\n` +
  `export const COMMIT_DATE = ${JSON.stringify(commitDate)};\n`;

writeFileSync(join(root, "ui/app/version.ts"), out);
console.log(`[sync-version] ui/app/version.ts -> ${version} · ${commitHash} · ${commitDate || "no-date"}`);
