// Regenerates ui/app/version.ts from app.config.json (app.version) plus git
// build metadata (short commit hash) and real build/deploy wall-clock times.
// Wired into the `build`, `start`, and `deploy` npm scripts so the in-app
// version footer and About page always match the deployed app — no manual
// edits needed.
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8"));
const version = cfg?.app?.version;

if (!version) {
  console.error("[sync-version] could not read app.version from app.config.json");
  process.exit(1);
}

function git(command, fallback) {
  try {
    return execSync(command, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

function extractField(text, name) {
  const match = text.match(new RegExp(`export const ${name} = "([^"]*)";`));
  return match ? match[1] : "";
}

const commitHash = git("git rev-parse --short HEAD", "unknown");
const commitDate = git("git log -1 --format=%cI", "");
const nowIso = new Date().toISOString();

const versionFile = join(root, "ui/app/version.ts");
let previousBuildDate = "";
let previousDeployDate = "";
if (existsSync(versionFile)) {
  const prev = readFileSync(versionFile, "utf8");
  previousBuildDate = extractField(prev, "BUILD_DATE");
  previousDeployDate = extractField(prev, "DEPLOY_DATE");
}

// npm sets npm_lifecycle_event to the script name for every process in the
// `npm run X` chain, so this script (invoked from within "build"/"start"/
// "deploy") can tell which one triggered it without any extra plumbing.
const lifecycle = process.env.npm_lifecycle_event;
const isBuildOrDeploy = lifecycle === "build" || lifecycle === "deploy";
const isDeploy = lifecycle === "deploy";

// BUILD_DATE tracks the last real production build (`build`/`deploy`), not a
// local `dev` server start. DEPLOY_DATE only advances on an actual `deploy` —
// both carry the previous value forward otherwise so the About page keeps
// showing the last real build/deploy instead of a dev-session timestamp.
const buildDate = isBuildOrDeploy ? nowIso : previousBuildDate || nowIso;
const deployDate = isDeploy ? nowIso : previousDeployDate;

const out =
  `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n` +
  `// Sourced from app.config.json (app.version) + git; regenerated on build/deploy.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n` +
  `export const COMMIT_HASH = ${JSON.stringify(commitHash)};\n` +
  `export const COMMIT_DATE = ${JSON.stringify(commitDate)};\n` +
  `export const BUILD_DATE = ${JSON.stringify(buildDate)};\n` +
  `export const DEPLOY_DATE = ${JSON.stringify(deployDate)};\n`;

writeFileSync(versionFile, out);
console.log(
  `[sync-version] ui/app/version.ts -> ${version} · ${commitHash} · build ${buildDate}` +
    (isDeploy ? ` · deployed ${deployDate}` : "")
);
