// Regenerates ui/app/version.ts from app.config.json (app.version).
// Wired into the `build` and `deploy` npm scripts so the in-app version footer
// always matches the deployed app version — no manual edits needed.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(readFileSync(join(root, "app.config.json"), "utf8"));
const version = cfg?.app?.version;

if (!version) {
  console.error("[sync-version] could not read app.version from app.config.json");
  process.exit(1);
}

const out =
  `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n` +
  `// Sourced from app.config.json (app.version); regenerated on build/deploy.\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n`;

writeFileSync(join(root, "ui/app/version.ts"), out);
console.log(`[sync-version] ui/app/version.ts -> ${version}`);
