// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Sourced from app.config.json (app.version) + git; regenerated on build/deploy.
export const APP_VERSION = "2.22.3";
export const COMMIT_HASH = "2860ec3";
export const COMMIT_DATE = "2026-08-26T08:41:00-05:00";
