// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Sourced from app.config.json (app.version) + git; regenerated on build/deploy.
export const APP_VERSION = "2.62.0";
export const COMMIT_HASH = "395143b";
export const COMMIT_DATE = "2026-08-31T21:33:29-05:00";
export const BUILD_DATE = "2026-09-01T02:44:35.297Z";
export const DEPLOY_DATE = "2026-09-01T02:44:35.297Z";
