// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Sourced from app.config.json (app.version) + git; regenerated on build/deploy.
export const APP_VERSION = "2.54.0";
export const COMMIT_HASH = "78cb6e1";
export const COMMIT_DATE = "2026-08-31T18:10:15-05:00";
export const BUILD_DATE = "2026-09-01T00:04:47.635Z";
export const DEPLOY_DATE = "2026-09-01T00:04:47.635Z";
